version: '3.8'
services:
    cosc304-mysql:
        image: mysql:8.0
        container_name: cosc304-mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'cosc304-mysql'
            MYSQL_USER: 'edward'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'rootpassword'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - mysql-db:/var/lib/mysql
            - ./ddl:/docker-entrypoint-initdb.d
volumes:
    mysql-db:
